name: bb
description: Firebase Authentication Helpers
version: 1.0.0
homepage: https://docs.aravi.me/packages/bb

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  google_sign_in: ^6.1.0
  meta: ^1.8.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  firebase_auth_platform_interface: ^6.15.0
  firebase_core_platform_interface: ^4.8.0

  flutter_lints: ^2.0.0
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.4
